<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>10.0.0-preview2</Version>
    <PackageProjectUrl>https://github.com/madebykrol/InteractR</PackageProjectUrl>
    <RepositoryUrl>https://github.com/madebykrol/InteractR</RepositoryUrl>
    <AssemblyVersion>10.0.0.3</AssemblyVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <Description>InteractR notification in- and outlet implementation using RabbitMQ</Description>
    <Authors>Kristoffer Olsson</Authors>
    <Company>Kristoffer Olsson</Company>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InteractR\InteractR.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.4" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

</Project>
